### ISSUE TITLE
Linked site not Working and Colored Toolbar Without Scrolling

### ISSUE THREAD

**Issue by mattbierner** [LeonKoole/RainbowSafari#8]
Thanks for the project.

The linked site (http://lym.io/RainbowSafari/) does not work for me on Safari 8 desktop or iOS8 Safari, though your other site (http://liamforsyth.co.uk/rainbow/) does. 

Also, if I'm not mistaken this approach requires scrolling before the effect becomes visible. On iOS, you can color the title bar before scrolling by setting the `body` background color. 

```
body {
    background: #00A8C9;
}
// Actual page background.
body:before {
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    position: fixed;
    content: "";
    display: block;
    z-index: -99;
    background: white;
}
````

Before:

![screen shot 2015-05-26 at 8 43 20 pm](https://cloud.githubusercontent.com/assets/212305/7828427/0da5195c-03e8-11e5-939b-086744b7c527.png)

And with the body color:

![screen shot 2015-05-26 at 8 43 07 pm](https://cloud.githubusercontent.com/assets/212305/7828428/152c4d6c-03e8-11e5-9c3a-9c0505c09f6b.png)

Only seems to work for solid colors though, no gradients or images, and only on iOS, not desktop Safari.

I'm using this approach on [Blot're](https://blot.re). You can see the effect in action on a page like this: https://blot.re/s/matt/weather

**Comment by LeonKoole** [comment]
I totally forgot to close this issue, because at the time this was issued, I wasn't sure if I wanted to give up desktop and animation support just to get it working before scroll on iOS. 

I'll soon be updating the repo with a new version of RainbowSafari that uses body:before to replace the `#rainbowsafari` element, but that means this implementation won't be used. I am therefor, almost a year after this was posted, closing the issue. This however still is a great solution if you just want to set a static color as title bar background on iOS devices.
